trigger: none

schedules:
- cron: "0 0 * * *"
  displayName: "Scheduled Scan"
  branches:
    include:
    - main
    - features/testing
    
pool:
  name: DevOpsLocal


variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

  - task: DotNetCoreCLI@2
    displayName: 'Run tests'
    inputs:
      command: test
      arguments: 'Wimc.Tests.Unit/Wimc.Tests.Unit.csproj'

  - task: CmdLine@2
    displayName: 'Sonar Scan'
    inputs:
      script: |
        dotnet-sonarscanner begin /k:"wimc-net" /d:sonar.host.url="http://sonarqube.sec.local:9000" /d:sonar.login="$(SONAR_TOKEN)"

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: build
      arguments: ' --configuration $(BuildConfiguration)'
      projects: '**/*.csproj'

  - task: CmdLine@2
    displayName: 'Collect Sonar Results and Upload'
    inputs:
      script: |
        dotnet-sonarscanner end /d:sonar.login="$(SONAR_TOKEN)"


