apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-db
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: {{.Values.applicationName}}-db
  type: ClusterIP
  ports:
  - port: 1433
    protocol: TCP
    targetPort: 1433