
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Release.Name}}-db
  namespace: {{.Release.Namespace}}
  labels:
    environment: {{.Values.applicationEnvironment}}
    app: {{.Values.applicationName}}-db
