apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  name: {{.Release.Name}}-proxy
  namespace:  {{.Release.Namespace}}
spec:
  rules:
  - host: {{.Values.hostName}}
    http:
      paths:
      - backend:
          service: 
            name: {{.Values.applicationName}}-proxy
            port: 
              number: 4180
        path: /oauth2
        pathType: Prefix
      - backend:
          service:
            name: {{.Values.applicationName}}-proxy
            port:
              number: 4180
        path: /oauth2/callback
        pathType: Prefix
  tls:
  - hosts:
    - {{.Values.hostName}}
    secretName: {{.Values.applicationName}}-secret