apiVersion: apps/v1
kind: Deployment
metadata:
  name: wimc-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wimc-proxy
  template:
    metadata:
      labels:
        app: wimc-proxy
    spec:
      containers:
      - args:
        - --provider=azure
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --azure-tenant=71352f15-6ebd-4c82-bbc2-8057b4a01373
        env:
          - name: OAUTH2_PROXY_CLIENT_ID
            value: b8344a47-5179-4288-a0f6-cb8b31e5a54e
          - name: OAUTH2_PROXY_CLIENT_SECRET
            value: xI~Z2--TSnF06vF_lcwXqjOic-~FnOfS31
          - name: OAUTH2_PROXY_COOKIE_SECRET
            value: RW5Kc21UZVJENkIxckVFbW81cEw0NTY0 # value of: echo -n <value> | base64'
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.3
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP