
applicationEnvironment: "wimc-dev"
applicationName: "wimc-worker"

# Deployment
replicaCount: 1

appImage: 
  repository: mxinfo.azurecr.io/wimc-worker
  pullPolicy: "IfNotPresent"
  tag: ""

resources:
  requests:
    cpu: 200m
    memory: 300Mi
  limits:
    cpu: 200m
    memory: 300Mi

dbresources:
  requests:
    cpu: 400m
    memory: 2000Mi
  limits:
    cpu: 400m
    memory: 2000Mi